name: Build and Deploy
on:
  push:
    branches:
      - main
jobs:
  build-and-deploy:
    if: "!contains(github.event.head_commit.message, 'ci skip')"
    runs-on: ubuntu-latest
    steps:
      - name: Checkout 🛎️
        uses: actions/checkout@v2
        with:
          persist-credentials: false

      - name: Install and Build.
        run: |
          npm install yarn
          yarn install
          yarn run deploy
      - name: deploy to s3
        uses: jakejarvis/s3-sync-action@master
        env:
          SOURCE_DIR: 'dist'
          AWS_S3_BUCKET: ${{ secrets.AWS_S3_BUCKET }}
          AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
          AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          AWS_REGION: 'us-west-2'